export const anger = 
[
    "When I am angry I use subtle insults to hurt others",
    "When I am angry, I will refuse to follow through on tasks to annoy or hurt someone else",
    "When I am angry, I will indirectly express it and only show others a false happy exterior",
    "When I am angry, I explore with rage no matter who is around me or where I am",
    "When I am angry, I am prone to get into fights and cause property damage",
    "When I am angry, I tend to respond in an extreme manner beyond what caused my anger",
    "I tend to hold grudges against those who I feel wronged me",
    "When I am angry, it sits inside of me and grows",
    "When I am angry, I tend to hold onto anger and disappointment at being treated unfairly",
    "I tend to hold onto thoughts of revenge",
    "I spend a lot of time thinking about how to get back at those who have hurt me",
    "I’d like to inflict hurt or harm on someone for an injury or wrong done to me",
    "I tend to hold onto my anger for 2 months or more",
    "I am angry all the time",
    "I tend to wake up angry, and I’m angry all day",
    "When a situation makes me angry, I’m still able to focus and work to resolve the situation",
    "When I am in a situation that angers me, my anger motivates me into action to resolve it",
    "If I get a product or service that is broken or bad, my anger will encourage me to address it and get it resolved",
    "I’m likely to get angry when someone else is being hurt or manipulated in a situation",
    "I tend to get angry when I feel that someone else should be angry about how they are being treated",
    "I get angry when I think that others are being mistreated",
    "When I am angry, I do not get into fights or cause property damage",
    "When I am angry, I remain calm no matter who is around me or where I am",
    "I tend to forgive those who I feel wronged me",
    "When I am angry, I still follow through on tasks regardless of my feelings"
]
