export const anxiety = [
    "I feel calm in the situations which are beyond my control.",
    "I feel secure",
    "I feel stressed in case of sudden changes or deadlines",
    "I have feeling of Nausea and stomach aches",
    "People's opinions matter to me.",
    "I try to control my situations and people around me",
    "I feel upset",
    "I am worried thinking about new situations",
    "I feel uncomfortable",
    "I feel self-confident",
    "I feel nervous and jittery",
    "I do not initiate conversations or ask questions",
    "I am afraid to speak up in classrooms or any formal settings",
    "I feel steady, pleasant, and in control of myself",
    "I am relaxed and contented",
    "Forgiving people is very difficult for me.",
    "I am worried thinking about different situations",
    "I feel being judged in social situations",
    "I prefer to be by myself rather than in a group",
    "I find my social battery drains quickly when I’m in any social situation",
    "I plan a lot before my exams or meeting people",
    "My mind goes blank during a test",
    "I have trouble sleeping the night before a test",
    "I forget the answers to a question even if I had studied it",
    "I think about my grades more than my efforts",
    "Comparison with my peers helps me to prepare better for exams",
    "Discussions just before the exams are very helpful",
    "I feel confident about my performance",
    "Deadlines and time frames help me to perform better",
    "I feel anxious in situations which are beyond my control.",
    "People's opinions do not matter to me.",
    "Forgiving people is very easy for me.",
    "I find my social battery stays full when I’m in any social situation."
  ];
  