import { Question } from "./anger";
export const depression: Question[] = [
  { question: "I like to resolve my conflicts by thinking rationally", reversal: false, type: []},
  { question: "Asking for help from my family and friends is easy for me in kind of situations", reversal: false, type: []},
  { question: "Reaching out to my friends in case of difficulty is easy", reversal: false, type: []},
  { question: "I like to think over and over on the smallest of the issues", reversal: false, type: []},
  { question: "I like to resolve my concerns myself instead of taking help", reversal: false, type: []},
  { question: "I feel guilty for my mistakes", reversal: false, type: []},
  { question: "I feel punished for my doings", reversal: false, type: []},
  { question: "I am critical of myself for my weakness or mistakes", reversal: false, type: []},
  { question: "I think about death without any pain", reversal: false, type: []},
  { question: "I feel irritated on the smallest of the things", reversal: false, type: []},
  { question: "I like to overeat in case of stressful situations", reversal: false, type: []},
  { question: "Food is the first thing I would like to avoid eating in case of stress", reversal: false, type: []},
  { question: "I get tired quickly", reversal: false, type: []},
  { question: "I am so worried about my physical problems that I cannot think of anything else", reversal: false, type: []},
  { question: "There's a sudden change in my weight", reversal: false, type: []},
  { question: "I avoid taking shower", reversal: false, type: []},
  { question: "Getting out of bed is the difficult thing", reversal: false, type: []},
  { question: "I have to push myself very hard to do anything", reversal: false, type: []},
  { question: "Food is the first thing I turn to in case of stress", reversal: false, type: []},
  { question: "I am forgiving of myself for my weakness or mistakes", reversal: true, type: []},
  { question: "I prefer to take help rather than resolving my concerns myself", reversal: true, type: []},
  { question: "Getting out of bed is easy. I find it effortless to get things done", reversal: true, type: []}
];
