export const ed = [
    "I believe I am overweight, even if not",
    "I feel the need to diet or control food",
    "I feel guilty and remorse when I eat",
    "I feel the need to exercise excessively to make up for what I have eaten",
    "I keep certain foods out of my diet",
    "I binge eat in a short span of time",
    "I am terrified of being overweight",
    "I isolate so that I can eat",
    "I avoid eating when I am hungry",
    "I continue to eat even after I feel full",
    "I take medication or exercise instead of eating a meal",
    "I feel out of control when I eat",
    "I make myself vomit to avoid gaining weight",
    "I regularly take laxatives or diuretics to lose weight",
    "I skip meals to lose weight or to avoid gaining weight",
    "I diet often",
    "I exercise more than once a day",
    "My emotions affect my eating habits",
    "I am preoccupied with food or my body size",
    "I avoid close relationships or social activities",
    "I feel my eating habits are impacting the quality of my life",
    "I believe I am at a healthy weight",
    "I feel in control when I eat",
    "I eat regular meals regardless of my weight",
    "My emotions do not affect my eating habits"
  ];
  