import { Question } from "./anger";

export const internet: Question[] = [
  { question: "I use electronic devices during my free time.", reversal: false, type: [] },
  { question: "I spend time on my smartphone, tablet, or computer each day.", reversal: false, type: [] },
  { question: "My academic performance has been affected by my gadget use.", reversal: false, type: [] },
  { question: "I sacrifice other activities to use my devices.", reversal: false, type: [] },
  { question: "I have experienced health issues due to gadget use.", reversal: false, type: [] },
  { question: "I am distracted by devices during classes.", reversal: false, type: [] },
  { question: "I prefer to use my devices for specific tasks, rather than for all my activities.", reversal: false, type: [] },
  { question: "I take my device with me when I go to the restroom.", reversal: false, type: [] },
  { question: "I check my social media accounts.", reversal: false, type: [] },
  { question: "I use words or phrases from the internet in my daily life.", reversal: false, type: [] },
  { question: "I become anxious about being without an internet connection for a short period.", reversal: false, type: [] },
  { question: "I buy products online when I can't find them locally.", reversal: false, type: [] },
  { question: "I use my allowance to purchase electronic devices or digital products.", reversal: false, type: [] },
  { question: "I have t-shirts with computer game, game character, or influencer-related designs.", reversal: false, type: [] },
  { question: "I know what a 'meme' is.", reversal: false, type: [] },
  { question: "I have been asked to reduce my device use by others.", reversal: false, type: [] },
  { question: "I meet friends through virtual games.", reversal: false, type: [] },
  { question: "I have two or fewer social media accounts.", reversal: false, type: [] },
  { question: "I have one or two battery chargers for my devices.", reversal: false, type: [] },
  { question: "I sometimes sit close to a power outlet to use my devices when charging.", reversal: false, type: [] },
  { question: "I spend a portion of my day looking at screens.", reversal: false, type: [] },
  { question: "I use internet abbreviations in my daily life.", reversal: false, type: [] },
  { question: "I sometimes skip a meal when I'm engrossed in my device.", reversal: false, type: [] },
  { question: "I have three or fewer open tabs on my internet browser at a time.", reversal: false, type: [] },
  { question: "I occasionally check my messages, social media, and emails during a movie.", reversal: false, type: [] },
  { question: "I do not become anxious about being without an internet connection for a short period.", reversal: true, type: [] },
  { question: "I have more than two social media accounts.", reversal: true, type: [] },
  { question: "I do not spend any part of my day looking at screens.", reversal: true, type: [] },
  { question: "I am not distracted by devices during classes.", reversal: true, type: [] }
];
