export const internet = [
    "I use electronic devices during my free time",
    "I spend time on my smartphone, tablet, or computer each day",
    "My academic performance has been affected by my gadget use",
    "I sacrifice other activities to use my devices",
    "I have experienced health issues due to gadget use",
    "I am distracted by devices during classes",
    "I prefer to use my devices for specific tasks, rather than for all my activities",
    "I take my device with me when I go to the restroom",
    "I check my social media accounts",
    "I use words or phrases from the internet in my daily life",
    "I become anxious about being without an internet connection for a short period",
    "I buy products online when I can't find them locally",
    "I use my allowance to purchase electronic devices or digital products",
    "I have t-shirts with computer game, game character, or influencer-related designs",
    "I know what a 'meme' is",
    "I have been asked to reduce my device use by others",
    "I meet friends through virtual games",
    "I have two or fewer social media accounts",
    "I have one or two battery chargers for my devices",
    "I sometimes sit close to a power outlet to use my devices when charging",
    "I spend a portion of my day looking at screens",
    "I use internet abbreviations in my daily life",
    "I sometimes skip a meal when I'm engrossed in my device",
    "I have three or fewer open tabs on my internet browser at a time",
    "I occasionally check my messages, social media, and emails during a movie",
    "I do not become anxious about being without an internet connection for a short period",
    "I have more than two social media accounts",
    "I do not spend any part of my day looking at screens",
    "I am not distracted by devices during classes"
  ];
  